controller:
  image: jenkins/jenkins
  tag: "2.426.1-jdk17"
  adminUser: "admin"
  adminPassword: "admin123"
  numExecutors: 0
  executorMode: "NORMAL"
  serviceType: ClusterIP
  servicePort: 8080
  targetPort: 8080
  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
    hostName: jenkins.example.com
    path: "/"
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 2000m
      memory: 4096Mi
  JCasC:
    defaultConfig: true
    configScripts:
      welcome-message: |
        jenkins:
          systemMessage: Welcome to our CI\CD server.
      kubernetes: |
        jenkins:
          clouds:
            - kubernetes:
                name: kubernetes
                serverUrl: https://kubernetes.default:443
                namespace: jenkins
                jenkinsUrl: http://jenkins.jenkins.svc.cluster.local:8080
                jenkinsTunnel: jenkins-agent.jenkins.svc.cluster.local:50000
                connectTimeout: 60
                readTimeout: 60
                maxRequestsPerHostStr: 32
                templates:
                  - name: "default"
                    namespace: "jenkins"
                    label: "jenkins-jenkins-agent"
                    nodeUsageMode: "NORMAL"
                    containers:
                      - name: jnlp
                        image: jenkins/inbound-agent:4.11.2-4
                        resourceRequestCpu: "512m"
                        resourceRequestMemory: "512Mi"
                        resourceLimitCpu: "512m"
                        resourceLimitMemory: "512Mi"
persistence:
  enabled: true
  existingClaim:
  storageClass: gp3
  accessMode: "ReadWriteOnce"
  size: "8Gi"
serviceAccount:
  create: true
  name: jenkins
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::992382587337:role/ise-lab-sandbox-jenkins-role
agent:
  enabled: true
  image: jenkins/inbound-agent
  tag: "4.11.2-4"
  workingDir: "/home/jenkins/agent"
  nodeUsageMode: "NORMAL"
  customJenkinsLabels: []
  resources:
    requests:
      cpu: "512m"
      memory: "512Mi"
    limits:
      cpu: "512m"
      memory: "512Mi"
